#!/usr/bin/env ruby

def current_dir
  File.expand_path(File.dirname(__FILE__))
end

def run_command(command)
  puts command
  `#{command}`
end

def listdirs(basenames)
  basenames.map { |dir| File.join(current_dir, dir) }
end

def listfiles(dirs)
  listdirs(dirs).map do |dir|
    Dir[File.join(dir, "*")] + Dir[File.join(dir, ".[^\.]*")]
  end.flatten
end

secrets = Hash.new
File.read(File.join(current_dir, 'secrets')).each_line do |line|
  if line =~ /^([^=]+)\s*=\s*([^=]+)$/
    secrets[$1.strip] = $2.strip
  end
end

unless Dir.exist? 'secret-files'
  Dir.mkdir 'secret-files'
end

listfiles(['files']).each do |infile|
  next unless infile =~ /\.in$/
  infilecontents = File.read(infile)
  secrets.each do |key, value|
    infilecontents.gsub! "{{ #{key} }}", value
  end
  file = File.open(infile.gsub(/\.in$/, '').gsub('/files/', '/secret-files/'), 'w')
  file.write infilecontents
  file.close
end

listfiles(['files', 'secret-files']).each do |file|
  next if file =~ /\.in$/
  run_command "ln -sfF #{file} $HOME/."
end

run_command "cd $HOME/.ssh; ln -sfF ../dotfiles/files/.ssh/* ."

%w(.vim/backup).each do |dir|
  run_command "mkdir -m 0700 -p $HOME/#{dir}"
end
